name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vlang/setup-v@v1.3
      - name: Test
        run: v -stats test ./rest

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vlang/setup-v@v1.3
      - name: Vet
        run: v vet -W .
